### ISSUE TITLE
Unable to install requirements on debian 9.3

### ISSUE THREAD

**Issue by dbrakman** [dpcomp-org/dpcomp_core#5]
The package python3.4-venv does not exist in the debian stretch repositories, so I installed python3-virtualenv instead. Otherwise, I started with a fresh VM of debian 9.3 and tried to follow the Readme instructions, executing:
`$ sudo apt-get update
$ sudo apt-get upgrade
$ sudo apt-get install python3 git
$ export DPCOMP_CORE=$HOME/Documents/dpcomp_core
$ export PYTHON_HOME=$HOME/virtualenvs/PyDpcomp
$ export PYTHONPATH=$PYTHONPATH:$DPCOMP_CORE
$ export DPCOMP_LOG_PATH=$HOME/logs
$ export DPCOMP_LOG_LEVEL=DEBUG
$ source $PYTHON_HOME/bin/activate
$ sudo apt-get install python3-virtualenv gfortran liblapack-dev libblas-dev 
$ sudo apt-get install libpq-dev python3-dev libncurses5-dev swig
$ git clone https://github.com/dpcomp-org/dpcomp_core.git
$ mkdir $DPCOMP_LOG_PATH
$ python3 -m venv $PYTHON_HOME
$ source $PYTHON_HOME/bin/activate
$ cd $DPCOMP_CORE
$ pip3 install -r resources/requirements.txt
`

The last line errors out, saying:
```Command "/home/me/virtualenvs/PyDpcomp/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-tp0rmm44/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-u980oeqo-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/me/virtualenvs/PyDpcomp/include/site/python3.5/scipy" failed with error code 1 in /tmp/pip-build-tp0rmm44/scipy/```

Is anyone else able to build on debian 9?

**Comment by gbiss** [comment]
Scipy does not officially support pip installation and it is flakey on some platforms. What has worked for me in similar circumstances is the following.

- remove scipy from requirements.txt
- install it system-wide, e.g. `apt install python-scipy`
- retry pip, `pip install -r requirements.txt`
