### ISSUE TITLE
HB2D with non-square matrices?

### ISSUE THREAD

**Issue by pratiksha** [dpcomp-org/dpcomp_core#6]
Hi, thanks for your work on this package! I'm attempting to run the HB2D algorithm with a non-square matrix (7 x 26 if it's useful). The code doesn't seem to assume a square matrix as input. However, the algorithm finds an optimal branching factor of 13 and then crashes with this error:

```
  File "/home/pratiksha/dev/software/dpcomp_core/dpcomp_core/algorithm/HB2D.py", line 52, in Run
    newx[i][:l2] = x[i]
ValueError: could not broadcast input array from shape (26) into shape (13)
```

Could someone explain whether this is a bug or, if not, how the algorithm is expected to behave here? (The cited paper Qardaji VLDB 2013 does seem to assume square matrices in the analysis in 5.1.) Thanks!

**Comment by horseno** [comment]
Thanks for your interest. Although not explicitly enforced, the implementation asks for a square matrix and uses a single branching factor for both dimensions.

**Comment by pratiksha** [comment]
Makes sense, thanks for the quick response!
